---

- name: Generate random UUID
  shell: uuidgen
  register: uuid_name

- name: Set uuid fact
  set_fact:
     server_name: "{{ uuid_name.stdout | replace('-','') }}"

- name: create server record with inventory
  uri:
    url: "{{ craton_url }}/hosts"
    method: POST
    body: '{"cloud_id": 1, "region_id": 1, "cell_id": 1, "name": "{{ server_name }}", "ip_address": "10.127.5.111", "device_type": "server"}'
    body_format: json
    status_code: 201
    headers:
      X-Auth-User: "{{ craton_user }}"
      X-Auth-Token: "{{ craton_key }}"
      X-Auth-Project: "{{ craton_project }}"
      Content-Type: application/json
  register: server_created

- name: set server_number to newly created host
  set_fact:
    server_number: "{{ server_created.json.id }}"
  when:
    - server_created.json.id is defined

- name: update server name to server-id
  uri:
    url: "{{ craton_url }}/hosts/{{ server_number }}"
    method: PUT
    body: '{"name": "server-{{ server_number }}"}'
    body_format: json
    status_code: 200
    headers:
      X-Auth-User: "{{ craton_user }}"
      X-Auth-Token: "{{ craton_key }}"
      X-Auth-Project: "{{ craton_project }}"
      Content-Type: application/json
  when:
    - server_created.json.id is defined

########### testing

- name: update variables on server with macs
  uri:
    url: "{{ craton_url }}/hosts/{{server_number}}/variables"
    method: PUT
    body: '{"macs": {{ hardware_macs.0 | to_json }} }'
  #  body: '{"macs": {{ hardware_macs | to_json }}}'
    body_format: json
    status_code: 200
    headers:
      X-Auth-User: "{{ craton_user }}"
      X-Auth-Token: "{{ craton_key }}"
      X-Auth-Project: "{{ craton_project }}"
      Content-Type: application/json
  when:
    - server_created.json.id is defined

- name: push up variables for testing
  uri:
    url: "{{ craton_url }}/hosts/{{server_number}}/variables"
    method: PUT
    body: "{\"{{ item.key }}\": \"{{ item.value }}\" }"
  #  body: '{"macs": {{ hardware_macs | to_json }}}'
    body_format: json
    status_code: 200
    headers:
      X-Auth-User: "{{ craton_user }}"
      X-Auth-Token: "{{ craton_key }}"
      X-Auth-Project: "{{ craton_project }}"
      Content-Type: application/json
  when:
    - server_created.json.id is defined
  with_items:
    - { key: 'ecopoiesis_bootstrapped', value: 'None' }
    - { key: 'ecopoiesis_boot_os', value: 'ubuntu' }
    - { key: 'ecopoiesis_boot_os_version', value: 'xenial' }
    - { key: 'ecopoiesis_boot_status', value: 'provision' }
    - { key: 'ecopoiesis_operational_status', value: 'None' }
    - { key: 'ecopoiesis_enforce_firmware', value: 'false' }
    - { key: 'datacenter', value: 'dfw' }
    - { key: 'primary_dns', value: '8.8.8.8' }
    - { key: 'secondary_dns', value: '8.8.4.4' }
    - { key: 'mgmt_ip_address', value: '1.2.3.4' }
    - { key: 'mgmt_gateway_ip', value: '1.2.3.1' }
    - { key: 'mgmt_netmask', value: '255.255.255.0' }
    - { key: 'server_name', value: 'this.is.a.test.com' }
