---

- include: discover_lldp.yml
  when:
    - host_id is not defined

- include: discover_mac.yml
  when:
    - host_id is not defined

- include: discover_create.yml
  when:
    - host_id is not defined

- name: set host_id to new_host_id if created
  set_fact:
    host_id: "{{ new_host_id }}"
  when:
    - new_host_id is defined

- debug:
    msg: "Server identified as Host ID: {{ host_id }}"
  when:
    - host_id is defined
